export const REGISTER_USER = 'REGISTER_USER';
export const USER_LOADED = 'USER_LOADED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_USER = 'LOGOUT_USER';
export const DELETE_USER = 'DELETE_USER';

export const GET_DB_QUESTIONS = 'GET_DB_QUESTIONS';
export const GET_DB_OPTIONS = 'GET_DB_OPTIONS';

export const ADD_QUESTIONS_AND_OPTIONS = 'ADD_QUESTIONS_AND_OPTIONS';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const SELECT_OPTION = 'SELECT_OPTION';

export const ADD_VOTE = 'ADD_VOTE';

export const CHANGE_MAIN_BODY = 'CHANGE_MAIN_BODY';

export const UPDATE_PHOTO = 'UPDATE_PHOTO';




