export const REGISTER_USER = 'REGISTER_USER';
export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';

export const GET_DB_QUESTIONS_AND_OPTIONS = 'GET_DB_QUESTIONS_AND_OPTIONS';

export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const SELECT_OPTION = 'SELECT_OPTION';
export const EDIT_OPTION = 'EDIT_OPTION';
export const DELETE_OPTION = 'DELETE_OPTION';



